// <auto-generated />
using System;
using BilirkisiAspire.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BilirkisiAspire.ApiService.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.Davaci", b =>
                {
                    b.Property<int>("DavaciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("AUdenHesapla")
                        .HasColumnType("bit");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DavaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DigerOdemeler")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("DilekceOzeti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GunlukCalismaSaati")
                        .HasColumnType("int");

                    b.Property<int?>("HaftalikCalismaGunu")
                        .HasColumnType("int");

                    b.Property<int?>("HaftalikEkCalismaSuresi")
                        .HasColumnType("int");

                    b.Property<int?>("HaftalikTatilGunu")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Ikramiye")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IseGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IstenCikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Prim")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TemelUcret")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("YemekUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("YolUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool?>("YuTopTasHesapla")
                        .HasColumnType("bit");

                    b.HasKey("DavaciId");

                    b.ToTable("Davacilar", (string)null);
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.DavaciVekili", b =>
                {
                    b.Property<int>("DavaciVekiliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DavaciVekiliId"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MahkemeDosyasiId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DavaciVekiliId");

                    b.HasIndex("MahkemeDosyasiId");

                    b.ToTable("DavaciVekilleri");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.Davali", b =>
                {
                    b.Property<int?>("DavaliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("DavaliId"));

                    b.Property<bool?>("AUdenHesapla")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DigerOdemeler")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("DilekceOzeti")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Ikramiye")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsimYaDaUnvan")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("MahkemeDosyasiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Prim")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("TemelUcret")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("YemekUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("YolUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool?>("YuTopTasHesapla")
                        .HasColumnType("bit");

                    b.Property<bool?>("ZamanAsimiItirazi")
                        .HasColumnType("bit");

                    b.HasKey("DavaliId");

                    b.HasIndex("MahkemeDosyasiId");

                    b.ToTable("Davalilar", (string)null);
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.DavaliVekili", b =>
                {
                    b.Property<int>("DavaliVekiliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DavaliVekiliId"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MahkemeDosyasiId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DavaliVekiliId");

                    b.HasIndex("MahkemeDosyasiId");

                    b.ToTable("DavaliVekilleri");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.EksikGunBildirimi", b =>
                {
                    b.Property<int?>("EksikGunBildirimiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("EksikGunBildirimiId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EksikGunBildirilenAy")
                        .HasColumnType("int");

                    b.Property<int?>("EksikGunBildirilenYil")
                        .HasColumnType("int");

                    b.Property<string>("EksikGunNedeni")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IstenCikisKodu")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SgkIncelemesiId")
                        .HasColumnType("int");

                    b.HasKey("EksikGunBildirimiId");

                    b.HasIndex("SgkIncelemesiId");

                    b.ToTable("EksikGunBildirimleri", (string)null);
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.HizmetSuresi", b =>
                {
                    b.Property<int?>("HizmetSuresiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("HizmetSuresiId"));

                    b.Property<DateTime?>("IseGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IstenCikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MahkemeDosyasiId")
                        .HasColumnType("int");

                    b.Property<bool>("SgkKayitlari")
                        .HasColumnType("bit");

                    b.Property<bool>("TalepleBaglilikIlkesi")
                        .HasColumnType("bit");

                    b.Property<bool>("TanikBeyanlari")
                        .HasColumnType("bit");

                    b.Property<bool>("UcretBordrolari")
                        .HasColumnType("bit");

                    b.HasKey("HizmetSuresiId");

                    b.HasIndex("MahkemeDosyasiId");

                    b.ToTable("HizmetSureleri");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.MahkemeDosyasi", b =>
                {
                    b.Property<int>("MahkemeDosyasiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MahkemeDosyasiId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DavaciId")
                        .HasColumnType("int");

                    b.Property<int>("DosyaYili")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("EsasNo")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MahkemeIli")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MahkemeSayisi")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UcretHesaplamaId")
                        .HasColumnType("int");

                    b.HasKey("MahkemeDosyasiId");

                    b.HasIndex("UcretHesaplamaId")
                        .IsUnique()
                        .HasFilter("[UcretHesaplamaId] IS NOT NULL");

                    b.ToTable("MahkemeDosyalari", (string)null);
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.Muzekkere", b =>
                {
                    b.Property<int?>("MuzekkereId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MuzekkereId"));

                    b.Property<string>("BildirilenUcret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MahkemeDosyasiId")
                        .HasColumnType("int");

                    b.Property<string>("YazilanKurum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MuzekkereId");

                    b.HasIndex("MahkemeDosyasiId");

                    b.ToTable("Muzekkereler");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.OdemeTalebi", b =>
                {
                    b.Property<int>("OdemeTalebiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdemeTalebiId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Bedel")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("DavaciId")
                        .HasColumnType("int");

                    b.HasKey("OdemeTalebiId");

                    b.HasIndex("DavaciId");

                    b.ToTable("OdemeTalepleri");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.PuantajKaydi", b =>
                {
                    b.Property<int>("PuantajKaydiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PuantajKaydiId"));

                    b.Property<int>("Ay")
                        .HasColumnType("int");

                    b.Property<decimal>("FazlaCalisma")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("Izin")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int?>("MahkemeDosyasiId")
                        .HasColumnType("int");

                    b.Property<bool?>("PuantajKayitlariVarYok")
                        .HasColumnType("bit");

                    b.Property<decimal>("UBGT")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("PuantajKaydiId");

                    b.HasIndex("MahkemeDosyasiId");

                    b.ToTable("PuantajKayitlari");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.SgkIncelemesi", b =>
                {
                    b.Property<int?>("SgkIncelemesiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SgkIncelemesiId"));

                    b.Property<int?>("CalisilanGun")
                        .HasColumnType("int");

                    b.Property<string>("IsverenUnvani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MahkemeDosyasiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SigortaIseGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SigortaIstenAyrilisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SigortaSicilNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SgkIncelemesiId");

                    b.HasIndex("MahkemeDosyasiId");

                    b.ToTable("SgkIncelemeleri");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.Tanik", b =>
                {
                    b.Property<int>("TanikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TanikId"));

                    b.Property<bool?>("AUdenHesapla")
                        .HasColumnType("bit");

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeyanOzeti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DavacininIseGirisSaati")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DavacininIsttenCikisSaati")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DigerOdemeler")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int?>("HaftaTatiliGunu")
                        .HasColumnType("int");

                    b.Property<int?>("HaftalikCalismaGunu")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("HaftalikEkCalismaSure")
                        .HasColumnType("time");

                    b.Property<bool?>("Husumet")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Ikramiye")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("MahkemeDosyasiId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Prim")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TaniginIseGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TaniginIstenCikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tarafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TemelUcret")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("YemekUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("YolUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool?>("YuTopTasHesapla")
                        .HasColumnType("bit");

                    b.HasKey("TanikId");

                    b.HasIndex("MahkemeDosyasiId");

                    b.ToTable("Taniklar");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.UcretBordrosu", b =>
                {
                    b.Property<int>("UcretBordrosuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UcretBordrosuId"));

                    b.Property<int>("Ay")
                        .HasColumnType("int");

                    b.Property<bool>("BankaDekontuVarYok")
                        .HasColumnType("bit");

                    b.Property<decimal>("FazlaCalisma")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("ImzaVarYok")
                        .HasColumnType("bit");

                    b.Property<decimal>("Izin")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int?>("MahkemeDosyasiId")
                        .HasColumnType("int");

                    b.Property<decimal>("Prim")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("UBGT")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool?>("UcretBordrosuVarYok")
                        .HasColumnType("bit");

                    b.Property<decimal>("YemekUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.Property<decimal>("YolUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("UcretBordrosuId");

                    b.HasIndex("MahkemeDosyasiId");

                    b.ToTable("UcretBordrolari");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.UcretHesaplama", b =>
                {
                    b.Property<int>("UcretHesaplamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UcretHesaplamaId"));

                    b.Property<bool>("AsgariUcretKatsayiAl")
                        .HasColumnType("bit");

                    b.Property<string>("AylikOrtalamaUcret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ElleGirilenYemekUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("ElleGirilenYolUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("GiydirilmisUcret")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("MeslekKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Prim")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("TemelUcret")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("UcretBordrolarindaHesapla")
                        .HasColumnType("bit");

                    b.Property<decimal?>("YemekUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("YolUcreti")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("UcretHesaplamaId");

                    b.ToTable("UcretHesaplamalari");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.Davaci", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.MahkemeDosyasi", "MahkemeDosyasi")
                        .WithOne("Davaci")
                        .HasForeignKey("BilirkisiAspire.Shared.Models.Davaci", "DavaciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MahkemeDosyasi");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.DavaciVekili", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.MahkemeDosyasi", "MahkemeDosyasi")
                        .WithMany("DavaciVekilleri")
                        .HasForeignKey("MahkemeDosyasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MahkemeDosyasi");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.Davali", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.MahkemeDosyasi", "MahkemeDosyasi")
                        .WithMany("Davalilar")
                        .HasForeignKey("MahkemeDosyasiId");

                    b.Navigation("MahkemeDosyasi");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.DavaliVekili", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.MahkemeDosyasi", "MahkemeDosyasi")
                        .WithMany("DavaliVekilleri")
                        .HasForeignKey("MahkemeDosyasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MahkemeDosyasi");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.EksikGunBildirimi", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.SgkIncelemesi", "SgkIncelemesi")
                        .WithMany("EksikGunBildirimleri")
                        .HasForeignKey("SgkIncelemesiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SgkIncelemesi");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.HizmetSuresi", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.MahkemeDosyasi", "MahkemeDosyasi")
                        .WithMany("HizmetSureleri")
                        .HasForeignKey("MahkemeDosyasiId");

                    b.Navigation("MahkemeDosyasi");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.MahkemeDosyasi", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.UcretHesaplama", "UcretHesaplama")
                        .WithOne("MahkemeDosyasi")
                        .HasForeignKey("BilirkisiAspire.Shared.Models.MahkemeDosyasi", "UcretHesaplamaId");

                    b.Navigation("UcretHesaplama");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.Muzekkere", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.MahkemeDosyasi", "MahkemeDosyasi")
                        .WithMany("Muzekkereler")
                        .HasForeignKey("MahkemeDosyasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MahkemeDosyasi");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.OdemeTalebi", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.Davaci", "Davaci")
                        .WithMany("OdemeTalepleri")
                        .HasForeignKey("DavaciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Davaci");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.PuantajKaydi", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.MahkemeDosyasi", "MahkemeDosyasi")
                        .WithMany("PuantajKayitlari")
                        .HasForeignKey("MahkemeDosyasiId");

                    b.Navigation("MahkemeDosyasi");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.SgkIncelemesi", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.MahkemeDosyasi", "MahkemeDosyasi")
                        .WithMany("SgkIncelemeleri")
                        .HasForeignKey("MahkemeDosyasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MahkemeDosyasi");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.Tanik", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.MahkemeDosyasi", "MahkemeDosyasi")
                        .WithMany("Taniklar")
                        .HasForeignKey("MahkemeDosyasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MahkemeDosyasi");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.UcretBordrosu", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.MahkemeDosyasi", "MahkemeDosyasi")
                        .WithMany("UcretBordrolari")
                        .HasForeignKey("MahkemeDosyasiId");

                    b.Navigation("MahkemeDosyasi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilirkisiAspire.Shared.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BilirkisiAspire.Shared.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.Davaci", b =>
                {
                    b.Navigation("OdemeTalepleri");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.MahkemeDosyasi", b =>
                {
                    b.Navigation("Davaci");

                    b.Navigation("DavaciVekilleri");

                    b.Navigation("DavaliVekilleri");

                    b.Navigation("Davalilar");

                    b.Navigation("HizmetSureleri");

                    b.Navigation("Muzekkereler");

                    b.Navigation("PuantajKayitlari");

                    b.Navigation("SgkIncelemeleri");

                    b.Navigation("Taniklar");

                    b.Navigation("UcretBordrolari");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.SgkIncelemesi", b =>
                {
                    b.Navigation("EksikGunBildirimleri");
                });

            modelBuilder.Entity("BilirkisiAspire.Shared.Models.UcretHesaplama", b =>
                {
                    b.Navigation("MahkemeDosyasi");
                });
#pragma warning restore 612, 618
        }
    }
}
